# -*- coding: utf-8 -*-
"""assignment3_RK1246.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLZ82xjyja-vNUofJYwLZnSpf7nhuDG6
"""

#Importing math module for the compounding interest formula

import math

#Assigning monetary values

def format_currency(amount):
    '''Formats a float value as currency with commas and two decimal places'''
    return "${:,.2f}".format(amount)

#Compound Interest Formula

def compound_interest(principal, interest_rate, compounding_frequency, years):
    """Calculates compound interest with given formula"""
    final_balance = principal * math.pow((1 + interest_rate / compounding_frequency), compounding_frequency * years)
    interest_earned = final_balance - principal
    return final_balance, interest_earned

#User Input and Showing Results

def main():
    """Main function to prompt a user to input info and display results"""
    print("Welcome to the Compound Interest Calculator.")

    #User Prompts

    principal = float(input("Please enter the initial amount of your investment: "))
    interest_rate = float(input("Please enter the interest rate (e.g., '0.3' for 3% interest): "))
    years = int(input("Please enter the number of years for investment: "))
    compounding_frequency = int(input("Please enter the number of compoundings per year: "))

    #Calculating Compound Interest

    final_balance, interest_earned = compound_interest(principal, interest_rate, years, compounding_frequency)

    #Results with output

    print("\nOriginal Investment: " + format_currency(principal))
    print("Interest Earned: " + format_currency(interest_earned))
    print("Final Balance: " + format_currency(final_balance))

if __name__ == '__main__':
    main()